spring:
  application:
    name: jooq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./h2/querydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true